#pragma once

#include "config.h" // IWYU pragma: keep
#include "types.h" // IWYU pragma: keep
#include "steroids/vec2.h"

static st_vec2_funcs_t st_vec2_simple_funcs = {
    .vec2_init               = st_vec2_init,
    .vec2_quit               = st_vec2_quit,
    .vec2_add                = st_vec2_add,
    .vec2_sum                = st_vec2_sum,
    .vec2_sub                = st_vec2_sub,
    .vec2_diff               = st_vec2_diff,
    .vec2_mul                = st_vec2_mul,
    .vec2_product            = st_vec2_product,
    .vec2_len                = st_vec2_len,
    .vec2_distance           = st_vec2_distance,
    .vec2_normalize          = st_vec2_normalize,
    .vec2_unit               = st_vec2_unit,
    .vec2_dot_product        = st_vec2_dot_product,
    .vec2_rangle             = st_vec2_rangle,
    .vec2_dangle             = st_vec2_dangle,
    .vec2_rrotate            = st_vec2_rrotate,
    .vec2_rrotation          = st_vec2_rrotation,
    .vec2_drotate            = st_vec2_drotate,
    .vec2_drotation          = st_vec2_drotation,
    .vec2_rotate90           = st_vec2_rotate90,
    .vec2_rotation90         = st_vec2_rotation90,
    .vec2_rotate180          = st_vec2_rotate180,
    .vec2_rotation180        = st_vec2_rotation180,
    .vec2_rotate270          = st_vec2_rotate270,
    .vec2_rotation270        = st_vec2_rotation270,
    .vec2_apply_matrix3x3    = st_vec2_apply_matrix3x3,
    .vec2_applying_matrix3x3 = st_vec2_applying_matrix3x3,
    .vec2_default_basis_xvec = st_vec2_default_basis_xvec,
    .vec2_default_basis_yvec = st_vec2_default_basis_yvec,
};

static st_modfuncentry_t st_module_vec2_simple_funcs[] = {
    {"init",               st_vec2_init},
    {"quit",               st_vec2_quit},
    {"add",                st_vec2_add},
    {"sum",                st_vec2_sum},
    {"sub",                st_vec2_sub},
    {"diff",               st_vec2_diff},
    {"mul",                st_vec2_mul},
    {"product",            st_vec2_product},
    {"len",                st_vec2_len},
    {"distance",           st_vec2_distance},
    {"normalize",          st_vec2_normalize},
    {"unit",               st_vec2_unit},
    {"dot_product",        st_vec2_dot_product},
    {"rangle",             st_vec2_rangle},
    {"dangle",             st_vec2_dangle},
    {"rrotate",            st_vec2_rrotate},
    {"rrotation",          st_vec2_rrotation},
    {"drotate",            st_vec2_drotate},
    {"drotation",          st_vec2_drotation},
    {"rotate90",           st_vec2_rotate90},
    {"rotation90",         st_vec2_rotation90},
    {"rotate180",          st_vec2_rotate180},
    {"rotation180",        st_vec2_rotation180},
    {"rotate270",          st_vec2_rotate270},
    {"rotation270",        st_vec2_rotation270},
    {"apply_matrix3x3",    st_vec2_apply_matrix3x3},
    {"applying_matrix3x3", st_vec2_applying_matrix3x3},
    {"default_basis_xvec", st_vec2_default_basis_xvec},
    {"default_basis_yvec", st_vec2_default_basis_yvec},
    {NULL, NULL},
};
