set(ST_MODULE_LOGGER_SIMPLE "internal" CACHE STRING "")
set(ST_MODULE_LOGGER_LIBSIR "internal" CACHE STRING "")
set(ST_MODULE_LUA_LUAJIT "no" CACHE STRING "")
set(ST_MODULE_OPTS_KETOPT "internal" CACHE STRING "")